import { AkiyaListing } from '@/types';

// TypeScript enforces the AkiyaListing shape on every object here.
// If you add a required field to the interface later, TypeScript will
// show an error on every listing that is missing it — no silent bugs.
export const mockAkiyaListings: AkiyaListing[] = [
  {
    listingId: 'akiya-001',
    title: 'Traditional Kominka — Noto Peninsula',
    prefecture: 'Ishikawa',
    city: 'Wajima',
    price: 1500000,
    imageUrl: 'https://images.unsplash.com/photo-1545579133-99bb5ab189bd?w=800&q=80',
    bedrooms: 4,
    sqMeters: 120,
    yearBuilt: 1965,
    description:
      'Stunning traditional farmhouse with original hand-hewn wooden beams and tatami rooms intact. Mountain views, peaceful village setting. Structurally sound — cosmetic renovation needed.',
    tags: ['kominka', 'mountain-view', 'renovation-needed'],
  },
  {
    listingId: 'akiya-002',
    title: 'Renovated Seaside Machiya — Amanohashidate',
    prefecture: 'Kyoto',
    city: 'Miyazu',
    price: 3800000,
    imageUrl: 'https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?w=800&q=80',
    bedrooms: 3,
    sqMeters: 90,
    yearBuilt: 1978,
    description:
      "Renovated machiya townhouse near one of Japan's three scenic views. New kitchen (2019), updated bath, modern insulation. Walking distance to beach and local izakayas.",
    tags: ['machiya', 'renovated', 'move-in-ready', 'seaside'],
  },
  {
    listingId: 'akiya-003',
    title: 'Large Farmhouse — Iya Valley, Tokushima',
    prefecture: 'Tokushima',
    city: 'Nishiawa',
    price: 800000,
    imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=80',
    bedrooms: 5,
    sqMeters: 180,
    yearBuilt: 1955,
    description:
      'Expansive farmhouse deep in the Iya Valley. Includes garden and terraced land. High renovation potential, municipality offers subsidy up to 1.5M yen.',
    tags: ['farmhouse', 'large', 'mountain-view', 'subsidy-eligible'],
  },
  {
    listingId: 'akiya-004',
    title: 'Compact Modern Home — Near UNESCO Silver Mine',
    prefecture: 'Shimane',
    city: 'Oda',
    price: 2200000,
    imageUrl: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&q=80',
    bedrooms: 2,
    sqMeters: 65,
    yearBuilt: 1990,
    description:
      'Well-maintained 1990 build close to Iwami Ginzan UNESCO World Heritage Site. Good broadband. Ideal for remote workers.',
    tags: ['modern', 'move-in-ready', 'compact', 'remote-work'],
  },
  {
    listingId: 'akiya-005',
    title: 'Free Transfer Property — Nagi Town',
    prefecture: 'Okayama',
    city: 'Nagi',
    price: 0,
    imageUrl: 'https://images.unsplash.com/photo-1448630360428-65456885c650?w=800&q=80',
    bedrooms: 3,
    sqMeters: 95,
    yearBuilt: 1970,
    description:
      'Offered free to a buyer committing to full-time residency and renovation. Subsidy covers up to 50% of qualified costs.',
    tags: ['free-transfer', 'subsidy-eligible', 'renovation-needed'],
  },
  {
    listingId: 'akiya-006',
    title: 'Restored Minka — Tanba Sasayama',
    prefecture: 'Hyogo',
    city: 'Tanba Sasayama',
    price: 4500000,
    imageUrl: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80',
    bedrooms: 3,
    sqMeters: 110,
    yearBuilt: 1962,
    description:
      'Completely restored traditional minka with modern amenities integrated. Exposed cedar beams, underfloor heating, new bath and kitchen.',
    tags: ['minka', 'fully-restored', 'move-in-ready'],
  },
];

export const prefectureOptions: string[] = [
  'All',
  'Hokkaido',
  'Aomori',
  'Iwate',
  'Miyagi',
  'Akita',
  'Yamagata',
  'Fukushima',
  'Ibaraki',
  'Tochigi',
  'Gunma',
  'Saitama',
  'Chiba',
  'Kanagawa',
  'Niigata',
  'Toyama',
  'Ishikawa',
  'Fukui',
  'Yamanashi',
  'Nagano',
  'Shizuoka',
  'Aichi',
  'Mie',
  'Shiga',
  'Kyoto',
  'Osaka',
  'Hyogo',
  'Nara',
  'Wakayama',
  'Tottori',
  'Shimane',
  'Okayama',
  'Hiroshima',
  'Yamaguchi',
  'Tokushima',
  'Kagawa',
  'Ehime',
  'Kochi',
  'Fukuoka',
  'Saga',
  'Nagasaki',
  'Kumamoto',
  'Oita',
  'Miyazaki',
  'Kagoshima',
  'Okinawa',
];
